# Generated by Django 4.0.3 on 2022-04-11 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name="User's likes"),
        ),
    ]
