# Generated by Django 4.0.1 on 2022-02-01 23:29

from django.db import migrations, models
import django.db.models.deletion
import src.base.services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Chief's name")),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, validators=[src.base.services.validate_fio], verbose_name='ФИО')),
                ('avatar', models.ImageField(upload_to='company/', verbose_name='Avatar')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('join_date', models.DateField(help_text='format: YYYY-MM-DD', verbose_name='Дата приёма на роботу')),
                ('salary', models.PositiveIntegerField(verbose_name='Заработная плата')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.chief')),
            ],
        ),
    ]
